#!/usr/bin/python
""" Call with a single argument to read that yaml and print out the merge. """

import sys
import os.path
import subprocess
import yaml
import json

from recursive_dictionary import RecursiveDictionary

PLUGIN_PATH = '/usr/lib/nagios/plugins'

base_yaml = RecursiveDictionary(yaml.safe_load(open('base-monitors.yaml','r')))
yamls = []
if len(sys.argv) > 1:
    for f in sys.argv[1:]:
        yamls.append(yaml.safe_load(open(f)))
else:
    cmon = json.loads(subprocess.check_output(['config-get','monitors','--format=json']))
    if cmon is not None and type(cmon) != dict:
        cmon = yaml.safe_load(cmon)
    if cmon is not None:
        yamls.append(cmon)
    if os.path.exists('primary-monitors.yaml'):
        with open('primary-monitors.yaml') as pm:
            yamls.append(yaml.safe_load(pm))

for y in yamls:
    if type(y) == dict:
        base_yaml.rec_update(y)

base_yaml = dict(base_yaml)

def make_command(mclass, mon):
    cmd_name = 'check_true'
    cmd_line = ['/usr/bin/true']

    if mclass == 'procrunning' or mclass == 'processcount':
        executable = mon.get('executable','')
        cmd_name = '%s_%s' % (mclass, executable.replace('/','_'))
        range_arg = '%s:%s' % (mon.get('min',''), mon.get('max',''))
        cmd = os.path.join(PLUGIN_PATH, 'check_procs')
        cmd_line = [cmd,'-w',range_arg,'-c',range_arg]
        if executable:
            cmd_line.extend(('-C',executable))
    elif mclass == 'mem':
        cmd_name = 'check_mem'
        cmd = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                '..', 'plugins', 'check_mem.pl'))
        cmd_line = [cmd, '-u', '-w', '85', '-c', '90']
    elif mclass == 'disk':
        path = mon.get('path','/')
        cmd_name = 'disk_%s' % (path.replace('/', '_'))
        cmd = os.path.join(PLUGIN_PATH, 'check_disk')
        cmd_line = [cmd, '-w', '20', '-c', '10', '-p', path]

    try:
        outpath = '/etc/nagios/nrpe.d/%s.cfg' % (cmd_name)
        with open(outpath, 'w') as cmdfile:
            cmdfile.write('command[%s]=%s' % (cmd_name, ' '.join(cmd_line)))
    except IOError:
        print 'cannot write to %s' % (outpath)
        print '%s=%s' % (cmd_name, ' '.join(cmd_line))
    return cmd_name

# Now transform local's into remote nrpe's
local = base_yaml['monitors'].get('local',{})
out_remotes = base_yaml['monitors'].get('remote',{})
for mclass, mons in local.iteritems():
    if 'nrpe' not in out_remotes:
        out_remotes['nrpe'] = {}
    if mclass == 'swap':
        # singles
        out_remotes['nrpe'][mclass] = {'command': 'check_%s' % mclass}
    elif mclass == 'mem':
        out_remotes['nrpe'][mclass] = {'command': make_command(mclass, {})}
    else:
        # Could have many
        for mname, mon in mons.iteritems():
            remote_key = '%s-%s' % (mclass, mname)
            command = make_command(mclass, mon)
            out_remotes['nrpe'][remote_key] = {'command': command}

if len(sys.argv) > 1:
    print yaml.safe_dump(base_yaml)
    sys.exit(0)

with open('monitors.yaml','w') as end_yaml:
    yaml.safe_dump(base_yaml, end_yaml)

subprocess.call(['service','nagios-nrpe-server','restart'])
