#!/usr/bin/python
import os
import json
import sys
import subprocess
import yaml

primary_id=os.environ.get('JUJU_REMOTE_UNIT','testing/0').replace('/','-')
if not os.path.exists('data'):
    os.mkdir('data')
with open('data/primary_id','w') as primid:
    primid.write(primary_id)

monitors = json.loads(subprocess.check_output(['relation-get','--format=json','monitors']))
if monitors is None or len(monitors) == 0:
    sys.exit(0)

with open('primary-monitors.yaml', 'w') as pmons:
    if type(monitors) == dict:
        yaml.safe_dump(monitors, pmons)
    else:
        pmons.write(monitors)
