#!/usr/bin/python

import glob
import yaml
import subprocess

# Clear out old ones
for name in glob.glob('/etc/nagios/nrpe.d/plugin-*.cfg'):
    os.unlink(name)

monitor_yaml = subprocess.check_output(['relation-get','monitors'])
# Primary will be merged with full
with open('primary-monitors.yaml','w') as primary:
    primary.write(monitor_yaml)

monitors = monitor_yaml.get('nrpe',[])

# Write new ones
for monitor,mattrs in monitors.iteritems():
    with open('/etc/nagios/nrpe.d/plugin-%s.cfg' % monitor, 'w'):
        args = mattrs.get('args','')
        if len(args):
            sep = ' '
        else:
            sep = ''
        monitor.write("command[%s]=%s%s%s" % (monitor, sep, args))

subprocess.check_call(['service','nagios-nrpe-server','reload'])
