#!/bin/bash
# This script should be idempotent.

set -e

. /usr/share/charm-helper/sh/net.sh
. hooks/nrpe.common.bash

# NRPE requires IP
address=$(ch_get_ip $(relation-get private-address))

juju-log "Adding $address to allowed_hosts."

target="$datadir/$JUJU_RELATION_ID-$unit_name"
mkdir -p $datadir
echo -n $address, > $target

# Use include dir instead
sed -i "s/^\(allowed_hosts=.*\)$/#\1/" /etc/nagios/nrpe.cfg

regen_allowed

service nagios-nrpe-server reload
