#!/bin/bash

nrpedir=/etc/nagios/nrpe.d

if [ ! -d $nrpedir ]; then
    action-fail "No $nrpedir exists"
    exit 1
else
  for i in $nrpedir/*.cfg; do
    if [ -f $i ]; then
      check=$(grep command $i | sed "s/command\[\(.*\\)]=\(.*\)$/\1/" | tr _ -);
      command=$(grep command $i | sed "s/command\[\(.*\\)]=\(.*\)$/\2/");
      action-set checks.$check="$command";
    fi
  done
fi

action-set timestamp="$(date)"
