name: Release to Edge

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # charmhelpers library is a submodule
          submodules: true

      - name: Initialize lxd  # This should dropped once it's implemented on charming-actions itself. https://github.com/canonical/charming-actions/issues/140
        # revision of latest main at time of writing; we need it for the fix for https://github.com/canonical/setup-lxd/issues/19
        uses: canonical/setup-lxd@2aa6f7caf7d1484298a64192f7f63a6684e648a4

      - name: Pack and upload to charmhub
        uses: canonical/charming-actions/upload-charm@2.6.2
        with:
          charmcraft-channel: "2.x/stable"
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          # Ensure the charm is built in an isolated environment and on the correct base in an lxd container.
          destructive-mode: false
